### PR TITLE
Update vulnerabilities list

### PR DESCRIPTION
**Pull request by pr0d33p**
Added some of the Top Mobile Application Security Vulnerabilities

### CODE REVIEW

**Comment by anuraghazra** [comment]
@TheBinitGhimire @ashiishme whoever manages this repo please review and merge the request

**Comment by pr0d33p** [comment]
@anuraghazra @ashiishme still not merged!

**Comment by pr0d33p** [comment]
will be adding soon

**Comment by ashiishme** [comment]
Keep contributing guys. Thanks for the support <3

**Pull request merged**
