### PR TITLE
Added Server-Side Template Injection

### PR DESCRIPTION
**Pull request by baibhavanand**

### CODE REVIEW

**Review by TheBinitGhimire — CHANGES_REQUESTED** [review]
Hi @baibhavanand, would you mind updating **`README.md`** as well alongside the **`vulnerabilities list`** file?

**Comment by baibhavanand** [comment]
@TheBinitGhimire 
Done!

**Review by TheBinitGhimire — CHANGES_REQUESTED** [review]
Hello @baibhavanand, the Markdown formatting isn't proper in **`README.md`**. Would you mind re-checking it?

And also, please include it under **Web Application Security Vulnerabilities** in **Table of Contents**!

3 changes required:
- Move from Mobile Application to Web Application in ToC,
- Fix the issue with unordered list inside **Web Application Security Vulnerabilities**,
- Take care of the internal hyperlink!

**Review by TheBinitGhimire — APPROVED** [review]
Hi @baibhavanand, the changes look fine now.

Thank you for contributing! Good Luck on your **Hacktoberfest 2020** journey!

**Comment by ashiishme** [comment]
Because of #13, this requires manual inspection. Sorry for that.

**Comment by baibhavanand** [comment]
Added a new pull request.

**Pull request closed without merging**
