### PR TITLE
Add new vulnerabilities to current list

### PR DESCRIPTION
**Pull request by GuillaumeFalourd**
## What I did

- Added new web application security vulnerabilities.
- Updated README file with new vulnerabilities.

Related to: https://github.com/askbuddie/vulnerabilities/issues/10

### CODE REVIEW

**Review by ashiishme — COMMENTED** [review]
Update the `readme.md` file too with the proper formatting.

**Review by TheBinitGhimire — CHANGES_REQUESTED** [review]
Hello @GuillaumeFalourd, as @ashiishme mentioned earlier, would you mind updating the **`README.md`** file as well?

**Comment by GuillaumeFalourd** [comment]
No problem, I'll do it later on today. Thank you.

**Comment by GuillaumeFalourd** [comment]
Done @ashiishme @TheBinitGhimire 👍

**Review by ashiishme — APPROVED** [review]
Fixed table of content. Looks good now.

**Pull request merged**
